- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable current nodejs
      ansible.builtin.command:
        cmd: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create expense user
      ansible.builtin.user:   # FIXED: replaced ansible.debug.user with ansible.builtin.user
        name: expense

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: expense        # Optional but recommended
        group: expense        # Optional but recommended
        mode: '0755'

    - name: download backend code  # FIXED: spelling from 'donwlad' to 'download'
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes   # FIXED: This must be true to use existing file on target

